name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 0 * * *" # runs daily
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate Pac-Man animation SVG
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: YugRokadia
          games: "pacman"   # comma-separate more, e.g. "pacman,breakout"

      - name: Push output to "output" branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
